---
region: "eu-west-2"

development_group: "ifbk"

component: "website"
deployment_identifier: "%{deployment_group}-%{deployment_type}-%{deployment_label}"

storage_bucket_name: "%{hiera('development_group')}-%{hiera('component')}-%{hiera('deployment_identifier')}-storage"
website_bucket_name: "%{hiera('development_group')}-%{hiera('component')}-%{hiera('deployment_identifier')}-content"

zone_domain_name: "infrablocks.io"

dns_zones_state_key: "dns-zones/deployment-state/default.tfstate"
website_state_key: "website/deployment-state/%{hiera('deployment_identifier')}.tfstate"

content_work_directory: "build/content"

non_standard_mime_types:
  font/woff2:
    - woff2

max_ages:
  image/jpeg: 300
  image/png: 300
  image/gif: 300
  image/svg+xml: 300
  text/html: 0
  text/css: 300
  application/javascript: 300
  application/font-woff: 2592000
  font/woff2: 2592000
