title: "InfraBlocks"
copyright_year: "2021"
description: "Modular infrastructure components and libraries"
author: "InfraBlocks Maintainers"

plugins:
  - "jekyll-postcss"
  - "jekyll-purgecss"
  - "jekyll-tidy"

exclude:
  - "ts"