title: "InfraBlocks"
copyright_year: "2020"
description: "Modular infrastructure components and libraries"
author: "Toby Clemson"

google_analytics:
  tracking_id: "UA-00000000-0"

sass:
  sass_dir: "_sass"

markdown: "kramdown"
plugins:
  - "jekyll-postcss"
  - "jekyll-purgecss"
  - "jekyll-tidy"
